/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedNuevoReporteRouteImport } from './routes/_authenticated/nuevo-reporte'
import { Route as AuthenticatedMuralRouteImport } from './routes/_authenticated/mural'
import { Route as AuthenticatedMisReportesRouteImport } from './routes/_authenticated/mis-reportes'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNuevoReporteRoute =
  AuthenticatedNuevoReporteRouteImport.update({
    id: '/nuevo-reporte',
    path: '/nuevo-reporte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMuralRoute = AuthenticatedMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisReportesRoute =
  AuthenticatedMisReportesRouteImport.update({
    id: '/mis-reportes',
    path: '/mis-reportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/nuevo-reporte': typeof AuthenticatedNuevoReporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/nuevo-reporte': typeof AuthenticatedNuevoReporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/_authenticated/mural': typeof AuthenticatedMuralRoute
  '/_authenticated/nuevo-reporte': typeof AuthenticatedNuevoReporteRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/historial'
    | '/inicio'
    | '/mis-reportes'
    | '/mural'
    | '/nuevo-reporte'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/historial'
    | '/inicio'
    | '/mis-reportes'
    | '/mural'
    | '/nuevo-reporte'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/historial'
    | '/_authenticated/inicio'
    | '/_authenticated/mis-reportes'
    | '/_authenticated/mural'
    | '/_authenticated/nuevo-reporte'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nuevo-reporte': {
      id: '/_authenticated/nuevo-reporte'
      path: '/nuevo-reporte'
      fullPath: '/nuevo-reporte'
      preLoaderRoute: typeof AuthenticatedNuevoReporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mural': {
      id: '/_authenticated/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof AuthenticatedMuralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-reportes': {
      id: '/_authenticated/mis-reportes'
      path: '/mis-reportes'
      fullPath: '/mis-reportes'
      preLoaderRoute: typeof AuthenticatedMisReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMisReportesRoute: typeof AuthenticatedMisReportesRoute
  AuthenticatedMuralRoute: typeof AuthenticatedMuralRoute
  AuthenticatedNuevoReporteRoute: typeof AuthenticatedNuevoReporteRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMisReportesRoute: AuthenticatedMisReportesRoute,
  AuthenticatedMuralRoute: AuthenticatedMuralRoute,
  AuthenticatedNuevoReporteRoute: AuthenticatedNuevoReporteRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
